## Application name
spring.application.name=AiTripPlanner
#
## DataSource configuration
#spring.datasource.url=jdbc:postgresql://localhost:5433/trip
#spring.datasource.username=postgres
#spring.datasource.password=9326
#
## Hibernate (JPA) settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#
## SQL initialization settings
spring.sql.init.mode=always
#
spring.main.allow-bean-definition-overriding=true
#
google.api.key=AIzaSyBfY6DeTJ2Y-e_hnbJDhtEgk7z02eLg6Io
#
#spring.application.name=BusBooking
#spring.jpa.hibernate.ddl-auto=update
#
#spring.datasource.url=jdbc:mysql://localhost:3306/busBooking_example
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true

# Application Name



# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/trip?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# add your mysql password if u have
